### ISSUE TITLE
Error: ant: not found

### ISSUE THREAD

**Issue by dubst3pp4** [shopwareLabs/shopware-docker#12]
Hello, when installing the development version of Shopware with

``$ ./psh.phar init-vcs --sw-branch=5.2``

I get the error:

``(4/5) Starting``
``> ant -f shopware/build/build.xml -Ddb.user=app -Ddb.password=app -Ddb.host=mysql -Ddb.name=shopware -Dapp.host=10.100.111.46 build-cache-dir build-config build-database build-generate-attributes build-snippets-deploy build-theme-initialize build-create-admin-account build-install-lock-file build-disable-firstrunwizard install-git-hooks``
``	sh: 1: ant: not found`` 

When I look into the Dockerfile of the php7 container, there is no command to install ant... Is it the correct place to put ant into this container?

**Comment by dubst3pp4** [comment]
Side-node: if you add the package ant into the Dockerfile, make sure to first add
``RUN mkdir -p /usr/share/man/man1``
else openjdk can't be installed...

**Comment by teiling88** [comment]
Feel free to create a pull request. In a previous version we had allready ant installed: 7478115b50e5b666b58ec98f991ca9038b3f2682

**Comment by almare** [comment]
Yes I had the same issue. I think the removal of ant is a problem specially if you offer a command init-vcs. Hopefully you add ant again.

**Comment by teiling88** [comment]
Fixed :)
