### ISSUE TITLE
Proposal: init-themes action

### ISSUE THREAD

**Issue by dubst3pp4** [shopwareLabs/shopware-docker#13]
It would be nice to have a ``init-themes`` action, that does basically what the ``init-plugins`` action does, that is:

1. the developer places the themes into a ``themes`` folder in the root directory of the project
2. the action creates a symlink in ``shopware/themes/Frontend`` for each theme of the folder

At the moment I'm solving this workflow with the following action (place it into ``dev-ops/common/actions/init-themes.sh``): [init-themes.txt](https://github.com/shopwareLabs/shopware-docker/files/2047636/init-themes.txt)

**Comment by teiling88** [comment]
Added with https://github.com/shopwareLabs/shopware-docker/commit/46cf0f28175aba310f3f6f6c28f7e49df9fc9755
Thank you for your contribution!
