### ISSUE TITLE
Connection timeout on mac

### ISSUE THREAD

**Issue by neomobil** [shopwareLabs/shopware-docker#14]
Hi people!
Thank you for this wonderful package. Everything looks like pretty good. The container is working, I can ssh in to the container. The only one thing is, I can not connect to the server with the URL http://10.100.111.46/
Maybe somebody has the same issue?

**Comment by dubst3pp4** [comment]
Please have a look at the [this comment](https://github.com/shopwareLabs/shopware-docker/issues/2#issuecomment-363387114) by @jonnitto

**Comment by neomobil** [comment]
Thanks, I'll check it.
