### ISSUE TITLE
SW-Console, DB connection has no driver

### ISSUE THREAD

**Issue by Miw0** [shopwareLabs/shopware-docker#15]
I set up a shopware environment like described in the read me and got my shop successfully runnig so thats fine :)

But when I want to use the SW-Console, like for generating theme configurations, I get the following error:
```
./bin/console sw:theme:dump:configuration
 WARNING! Could not connect to database. Message from SQL Server: could not find driver in /home/mw/docker/shopware-docker/shopware/engine/Shopware/Components/DependencyInjection/Bridge/Db.php 
                                                                                                              
  [Symfony\Component\DependencyInjection\Exception\RuntimeException]                                              
  You have requested a synthetic service ("db_connection"). The DIC does not know how to construct this service. 
```
Same with command `./bin/console sw:snippets:to:db` and I guess with every other database command.

How to fix this?

**Comment by Miw0** [comment]
Okay lol nevermind. I need to SSH into the container first :( Sorry! Can be closed.

**Comment by artursopelnik** [comment]
I have a similar problem but without errors.

Try to dump a new configuration file with `./bin/console sw:theme:dump:configuration` are not work. 

config-file are not generated.
