### ISSUE TITLE
Build fails on openjdk-8-jdk and openjdk-8-jre-headless

### ISSUE THREAD

**Issue by Isengo1989** [shopwareLabs/shopware-docker#22]
Seems like debian jessie does not have openjdk-8-jre-headless and openjdk-8-jdk

**Error**

> E: Unable to locate package openjdk-8-jre-headless
> Service 'app_server' failed to build: The command '/bin/sh -c apt-get update -qq && apt-get install -y -qq apt-utils && mkdir -p /usr/share/man/man1     && apt-get update -qq && apt-get install -y -qq openjdk-8-jre-headless     && apt-get update -qq && apt-get install -y -qq  openjdk-8-jdk && dpkg --configure -a' returned a non-zero code: 100
>         
> Execution aborted, a subcommand failed!

**Comment by JonnyCarter** [comment]
I get the same error trying to install on my machine. 
Removing  the following from `dev-ops/docker/containers/php7/Dockerfile` got it running for me.
```
RUN apt-get update -qq && apt-get install -y -qq apt-utils && mkdir -p /usr/share/man/man1 \
    && apt-get update -qq && apt-get install -y -qq openjdk-8-jre-headless \
    && apt-get update -qq && apt-get install -y -qq  openjdk-8-jdk && dpkg --configure -a
```

**Comment by Isengo1989** [comment]
Yes this is what I am doing also

**Comment by teiling88** [comment]
@Isengo1989 it works on my machine :see_no_evil: 

Did you build the container with php 7.1 oder 7.2?

**Comment by Isengo1989** [comment]
@teiling88 I build the container with whatever is written in the Dockerfile ^^

`FROM php:7.1-apache`

**Comment by Isengo1989** [comment]
My PR (https://github.com/shopwareLabs/shopware-docker/pull/24/files) actually should not delete all 3 command lines, just the one with openjdk - worked fine afterwards.

What distro are you using? Not that it should make a difference, but something seems off.

**Comment by teiling88** [comment]
Im using Ubuntu 16.04 LTS at the moment. 

How did you start the containers? With `./psh.phar docker:start` ?

**Comment by Padrio** [comment]
So will anything happen here soon? @teiling88 
I'm on macOS Mojave. Checked out the repository and ran `./psh.phar docker:start`which results in the error stated in this issue.

**Comment by larsbo** [comment]
Tested this repo today with clean Mojave installation (upgraded from High Sierra), got no error. After installation I had to add the fix from issue #2 and start the phar command again to make the shop work in browser.

**Comment by Padrio** [comment]
Thanks to my docker loving roommate @janfoerste: It's a docker cache issue.
Just purge your docker containers using `docker container prune -a` and execute `./psh.phar docker:start` again. Execute carefully, **deletes all your containers**.

**Comment by Isengo1989** [comment]
@JonnyCarter @Padrio I could fix this by updating docker and cleaning all images/containers

Before I was using 17.12.0 and I updated to 18.06.1 (docker).
