### ISSUE TITLE
Boot stuck on step 8

### ISSUE THREAD

**Issue by byzbro** [shopwareLabs/shopware-docker#29]
Hi,

is just wanted to build the repository. I cloned, cd into the cloned project and build it with ./psh.phar docker:start .

But at this point, nothing else is happening and it seems like the build is stuck:
Step 8/9 : RUN /tmp/createuser.sh
	 ---> Running in 003803d86123
	Enter new UNIX password: Retype new UNIX password: passwd: password updated successfully

**Comment by mjpr263** [comment]
Try to start the docker:start with "sudo ./psh.phar docker:start"
Worked for me, unfortunately i got other errors in the next steps. ;)

**Comment by teiling88** [comment]
is your user assigned to the docker group?

**Comment by teiling88** [comment]
Closed caused of inactivity!
