### ISSUE TITLE
Extremely slow on Mac

### ISSUE THREAD

**Issue by joergviola** [shopwareLabs/shopware-docker#32]
Hola,
thanks for providing these containers. Alas, they work extremely slow on my MacBook Pro.
I am an absolute shopware beginner. Installation went okay with no errors I am aware of.
Login and each operation in Front- and backend last minimum around 30 seks, sometimes minutes.

I did a native installation (without docker) and that is running smooth.

Context as far as I am aware of:

MacBook Pro 15", 2016
macOS Mojave 10.14.2
Docker version 18.09.0, build 4d60db4

What else do you need to know?

Thanks for your attention!
Saludos, Jörg

**Comment by shyim** [comment]
That is "normal" on OSX. The filesystem access is very very slow. 

But there are some detours which can make the performance better. Google for it 😊

**Comment by shyim** [comment]
And test the PR https://github.com/shopwareLabs/shopware-docker/pull/10

**Comment by joergviola** [comment]
Thanks *very much* for the support.
Now that I have it, I will stick with the native installation - thank you!
