### ISSUE TITLE
scruptcreator.sh doesnt work

### ISSUE THREAD

**Issue by tbadke** [shopwareLabs/shopware-docker#36]
Line 12 in file scriptcreator.sh ist incorrect. It is not possible to create a user with uuid 0, it says.
Dirty fix: 
`groupadd -o -g ${GROUP} app-shell`

For user: change this line before call:
`$ ./psh.phar docker:start`

**Comment by teiling88** [comment]
Please provide some detailed information to reproduce your issue like your os and your docker version.

**Comment by tbadke** [comment]
Sorry.
OS: Ubuntu 18.04.2 LTS
Docker: 18.06.1-ce
Docker-compose: 1.17.1

To reproduce this issue have to clone the git-repo and after run `$ ./psh.phar docker:start`.
While it runs it throws some errors; it can' create user and also cant login some times.
So it is not possible to start ES and MySql container.

I hope it helps.
Mein Englisch ist auch nicht gerade das Beste :D

**Comment by tbadke** [comment]
Sry, the dirty fix is:
`useradd -s /bin/bash -m -g ${GROUP} app-shell`

Wrong line :D

**Comment by shyim** [comment]
The issue is that you run it as root

**Comment by tbadke** [comment]
Oh sh*t :/ Yeah, thanks!!!
I installed it that way :D It works, so...
*embarrassing..*
