### ISSUE TITLE
Cant use grunt locally

### ISSUE THREAD

**Issue by aloiki** [shopwareLabs/shopware-docker#38]
Hello, 

I followed this [documentation](https://developers.shopware.com/designers-guide/best-practice-theme-development/?_ga=2.164706936.697468294.1557317884-453703276.1557317883#search-results) to use grunt for local development in Shopware and I want to use it in synergy with shopware-docker.

After installing node and grunt I wanted to clear the cache to generate the config files. 
At this step running  
```
cd var/cache/
./clear_cache.sh
```
I get the error in the terminal: 
```
Clearing caches WARNING! Could not connect to database. Message from SQL Server: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Users/truasl/work/shopware-docker/shopware/engine/Shopware/Components/DependencyInjection/Bridge/Db.php 

In Container.php line 334:
The "db_connection" service is synthetic, it needs to be set at boot time before it can be used. 
```

Can anybody help me out with this issue? 🙏🏻

**Comment by teiling88** [comment]
Please try this: 
```bash
./psh.phar docker:ssh
./var/cache/clear_cache.sh
```

**Comment by aloiki** [comment]
I tried to run these commands, but I am getting the same error...

The steps I am doing right now: 
**1. start docker**
`./psh.phar docker:start`

**2. SSH into Container**
`./psh.phar docker:ssh`

**3. Try to clear Cache**
`cd shopware/var/cache/clear_cache.sh`

**Comment by aloiki** [comment]
Also if I am trying to run _SW CLI-Commands_ and checking for all _CLI-Commands_ I am getting the same warning when I am trying to clear the cache or dump the theme configuration: 

```WARNING! Could not connect to database. Message from SQL Server: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /Users/truasl/work/shopware-docker/shopware/engine/Shopware/Components/DependencyInjection/Bridge/Db.php```

**Comment by shyim** [comment]
The file name from the output indicates that are you not in the docker container, cause its mac folder path.

Are you sure that docker:ssh has worked?

**Comment by aloiki** [comment]
omg that was so dumb! Thanks for your comment and just opening my eyes. So you can close this issue.
