### ISSUE TITLE
What was the intention to use a psh stuff for that?

### ISSUE THREAD

**Issue by KaySchneider** [shopwareLabs/shopware-docker#39]
In my opinion this docker implementation is fine for you guys ;-) 

But with that psh stuff, this is not portable ;-) You first has to install psh to run a docker container ;-) hmmmm  

So the idea behind docker is to integrate all fancy, crazy stuff into that docker container.    
That current implementation is not really helpfull. So there are tons well integrated builder to create docker-images, and hey you are using docker-compose to do so. 

And if you need to install or add something then let do it inside the container not outside. ;-)    Or use a simple shell script ;-) 

So the intention was good, but the solution wont, my mind. Are there any plans to create well supported and working docker images for docker hub ? Without fancy psh stuff ?

**Comment by shyim** [comment]
Thats one of my pain points, because i built https://github.com/shyim/shopware-docker :sweat_smile:

**Comment by teiling88** [comment]
> Are there any plans to create well supported and working docker images for docker hub?

To keep the answer short: no ;-)
