### ISSUE TITLE
Xdebug not configured

### ISSUE THREAD

**Issue by TobiasGraml11** [shopwareLabs/shopware-docker#43]
Hello,

I installed this Repo for plugin development, but xdebug was not configured correctly.
`php -v` doesn't show an installation of xdebug

**I fixed it with following steps:**

Added `COPY docker-php-ext-xdebug.ini /usr/local/etc/php/conf.d/` to php7 Dockerfile
Added 'docker-php-ext-xdebug.ini' with line `zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so`

Reporting it so you could maybe check this out. Took me a while to get to this solution.

Cheers,
Tobias

**Comment by teiling88** [comment]
Hey @TobiasGraml11,

thank you for your Information. I fixed it with https://github.com/shopwareLabs/shopware-docker/commit/d0c4eee2b98d8a2de08cf641f03b452746a3384a.

Thanks!
