### ISSUE TITLE
Access to backend works but access to frontend always results in redirect (301) to localhost.

### ISSUE THREAD

**Issue by abinder-1** [shopwareLabs/shopware-docker#47]
I successfully installed shopware-docker as described.

I installed it on a separate Debian based machine in my network. There is no problem to access the backend via <MACHINE_IP>:8083/backend by clients within the network.

But when I try to call <MACHINE_IP>:8083 there always happens a redirect to localhost:8083 which ends up in a refused connection for the clients because there is no server running from their point of view.

The Server Log looks like that: There you can see the the 301 (redirect).

`docker.vm:80 192.168.12.77 - - [07/Oct/2019:11:45:14 +0000] "GET / HTTP/1.1" 301 614 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0"
[httpd:access] 172.23.16.70:80 - - 192.168.12.77 - - [07/Oct/2019:11:45:14 +0000] "GET / HTTP/1.1" 301 bytesIn:791 bytesOut:614 reqTime:0
127.0.0.1 -  07/Oct/2019:11:45:14 +0000 "GET /shopware.php" 301 /var/www/shopware/shopware/shopware.php cpu:82.29% mem:2 reqTime:0.134`

I searched the `docker-compose.yml` and the` .htaccess`  files to find out where the redirect happens but was not able to find something useful.

Can you please help me? Do you know why the access to the backend is not redirected while the access to the frontend is?

**Comment by teiling88** [comment]
Hey Abinder,
enter here https://github.com/shopwareLabs/shopware-docker/blob/master/.psh.yaml.dist#L9 your <MACHINE_IP>:8083 and make a new init. Then it should work. 

> Do you know why the access to the backend is not redirected while the access to the frontend is?

The frontend is redirected to the configured shop url and in this case it is localhost:8083. The backend didn' have this kind of redirection :-)

Greetings, 
Thomas

**Comment by abinder-1** [comment]
Perfect, thank you very much, Thomas!

Now it can see the shop's frontend :-) 

Greetings
abinder
