### ISSUE TITLE
./psh.phar docker:start gives "/usr/bin/env: ‘php’: No such file or directory"

### ISSUE THREAD

**Issue by raoraafe** [shopwareLabs/shopware-docker#52]
Why the php is required to be installed to run the command for docker? 

What am i missing? i'm unable to proceed further after clone.

**Comment by rafaytaher** [comment]
ok I have found requirements for shopware install on docker on the link below.
php is required.
https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/requirements

**Comment by raoraafe** [comment]
ok I have found requirements for shopware install on docker on the link below.
php is required.
https://docs.shopware.com/en/shopware-platform-dev-en/getting-started/requirements
