### ISSUE TITLE
Not working under windows

### ISSUE THREAD

**Issue by mschop** [shopwareLabs/shopware-docker#7]
When trying to run "php psh.phar docker:start" I get the following error:

(1/6) Starting
> echo "COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}"
        "COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}"

(2/6) Starting
> dev-ops/docker/containers/scriptcreator.sh
        Der Befehl "dev-ops" ist entweder falsch geschrieben oder
        konnte nicht gefunden werden.
        (The command dev-ops is either wrong spelled or could not be found)

**Comment by teiling88** [comment]
Hey Mschop, 

unfortunately nobody from us uses windows with docker so this repo is not tested against it. If you want you can provide a pull request for this to fix it. 

Greetings, Thomas
